OnlineStore/Models/Chat.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineStore.Models
{
    public class Chat
    {
        public int id { get; set; }
        public string User { get; set; }
        public string message { get; set; }
        public DateTime DateTime { get; set; }
    }
}

OnlineStore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using OnlineStore.Models;

namespace OnlineStore.Controllers
{
    public class HomeController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
           var user =  User.Identity.GetUserId();
            bool isLogged;
            if(user != null)
            {
                isLogged = true;
                ViewBag.IsAdmin = db.Users.Where(m => m.Id == user).FirstOrDefault().IsAdmin;
            }
            else
            {
                isLogged = false;
            }       
            ViewBag.IsLoggedIn = isLogged;
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Help()
        {
            return View();
        }
        [Authorize]
        public ActionResult Chat()
        {
            var user = User.Identity.GetUserId();
            var email = db.Users.Where(m => m.Id == user).FirstOrDefault().Email; 
            ViewBag.Email = email;
            return View();
        }
    }
}

OnlineStore/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Microsoft.AspNet.Identity;
using OnlineStore.Helper;
using OnlineStore.Models;

namespace OnlineStore.Controllers
{
    public class ItemController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        int totaltake = 12;    //TOTAL TAKE
        #region Add Items for Sale

        // GET: AddItems
        [Authorize]
        public ActionResult AddItems()
        {
            //var listItems = new List<ListItem> 
            //{ 
            //      new ListItem { Text = "Mobile", Value = "Mobile" }, 
            //      new ListItem { Text = "Computers", Value = "Computers" },
            //      new ListItem { Text = "Pets", Value = "Pets" },
            //      new ListItem { Text = "Hobbies", Value = "Hobbies" },
            //      new ListItem { Text = "Motorcycle", Value = "Motorcycle" },
            //      new ListItem { Text = "Appliances", Value = "Appliances" },
            //      new ListItem { Text = "Furniture", Value = "Furniture" },
            //      new ListItem { Text = "Cars", Value = "Cars" },
            //       new ListItem { Text = "Clothes", Value = "Clothes" },
            //            new ListItem { Text = "Health", Value = "Health" },
            //                 new ListItem { Text = "Beauty", Value = "Beauty" }

            //};

            var listCondition = new List<ListItem>
            {
                new ListItem { Text = "Brand New", Value = "Brand New" },
                new ListItem { Text = "Secondhand", Value = "Secondhand" } 
            };

            //ViewBag.CategoryList = listItems;
            ViewBag.CategoryList = new SelectList(db.ItemType.OrderBy(m => m.ItemTypeName), "ItemTypeName", "ItemTypeName");
            ViewBag.ConditionList = listCondition;
            return View();
        }

        // POST: AddItems
        [HttpPost]
        [Authorize]
        public ActionResult AddItems(ItemsViewModel itemsViewModel, HttpPostedFileBase[] itemimages)
        {
            //Add value to master table
            ItemMaster master = new ItemMaster()
            {
                ItemName = itemsViewModel.ItemMaster.ItemName,
                DatePosted = DateTime.Now,
                UserId = User.Identity.GetUserId(),
                ContactNumber = itemsViewModel.ItemMaster.ContactNumber,
                EmailAddress = itemsViewModel.ItemMaster.EmailAddress,
                Location = itemsViewModel.ItemMaster.Location,
                IsApproved = "Draft",
                Availability = "Available"
            };
            db.ItemMaster.Add(master);

            ItemDetails details = new ItemDetails()
            {
                ItemDescription = itemsViewModel.ItemDetails.ItemDescription,
                ItemAmount = itemsViewModel.ItemDetails.ItemAmount,
                ItemCategory = itemsViewModel.ItemDetails.ItemCategory,
                ItemCondition = itemsViewModel.ItemDetails.ItemCondition,
                ItemMaster = master
            };

            db.ItemDetails.Add(details);
            db.SaveChanges();
            try
            {
                /*Loop for multiple files*/
                foreach (HttpPostedFileBase file in itemimages)
                {
                    ItemImages images = new ItemImages()
                    {
                        //Convert Images to byte to save to database
                        ItemPictures = CommonHelper.ConvertImageToByteArray(file),
                        ItemMaster = master
                    };

                    db.ItemImages.Add(images);
                    db.SaveChanges();
                }
            }
            catch
            {
                ViewBag.Message = "Error while uploading the files.";
            }

            return RedirectToAction("Index", "Home");
        }

        #endregion

        #region View Items for Sale
        // GET: ViewItems

        public ActionResult ViewItems(string category, string condition, string itemName, int page = 1)
        {
            #region populate dropdown
            var listCondition = new List<ListItem>
            {
                new ListItem { Text = "Brand New", Value = "Brand New" },
                new ListItem { Text = "Secondhand", Value = "Secondhand" } 
            };


            ViewBag.CategoryList = new SelectList(db.ItemType.OrderBy(m => m.ItemTypeName), "ItemTypeName", "ItemTypeName");
            ViewBag.ConditionList = new SelectList(listCondition, "Text", "Text");
    

            if (page == 0)
            {
                page = 1;
            }


            #endregion

            //List<ItemsViewModel> ItemsVm = new List<ItemsViewModel>();
            var ItemsVm = new List<ItemForSaleViewModel>();
            var dba = db.ItemMaster.Where(m=>m.Availability != "Reserved");
            var master = dba.ToList();
            if (!String.IsNullOrEmpty(itemName))
            {
                master = dba.Where(m => m.ItemName.Contains(itemName)).ToList();
            }


            foreach (var item in master)
            {

                bool isPrem;
                var checker = db.PremiumUsers.Where(m => m.UserId == item.UserId).FirstOrDefault();

                if (checker == null)
                {
                    isPrem = false;
                }
                else
                {
                    if (checker.IsPremium == true)
                    {
                        isPrem = true;
                    }
                    else
                    {
                        isPrem = false;
                    }
                }

                var temp = new ItemForSaleViewModel()
                {
                    ItemName = item.ItemName,
                    defaultImage = db.ItemImages.Where(m => m.ItemMaster.ItemId == item.ItemId).FirstOrDefault().ItemPictures,
                    ItemPrice = db.ItemDetails.Where(m => m.ItemMaster.ItemId == item.ItemId).FirstOrDefault().ItemAmount,
                    ItemMasterId = item.ItemId,
                    category = db.ItemDetails.Where(m => m.ItemMaster.ItemId == item.ItemId).FirstOrDefault().ItemCategory,
                    condition = db.ItemDetails.Where(m => m.ItemMaster.ItemId == item.ItemId).FirstOrDefault().ItemCondition,
                    isPremium = isPrem,
                    isApproved = item.IsApproved
                };
                ItemsVm.Add(temp);

            }
            //THISSSSSSS
            if (!String.IsNullOrEmpty(category) && !String.IsNullOrEmpty(condition))
            {
                var model = ItemsVm.Where(m => m.category == category).Where(m => m.condition == condition).Where(m => m.isApproved == "Approved").Where(m => m.Availability == "Available").ToList();

                ViewBag.PageCount = new SelectList(generatePageList(getPage(model.Count())), "Text", "Text");

                if (page == 1)
                {
                    int totalskip = page * totaltake;
                    return View(model.Take(totaltake).ToList());
                }
                else if (page == 2)
                {
                    int totalskip = totaltake;
                    return View(model.Skip(totalskip).Take(totaltake).ToList());
                }
                else
                {
                    int totalskip = (page - 1) * totaltake;
                    return View(model.Skip(totalskip).Take(totaltake).ToList());
                }
            }
            else if (!String.IsNullOrEmpty(category) && String.IsNullOrEmpty(condition))
            {
                var model = ItemsVm.Where(m => m.category == category).Where(m => m.isApproved == "Approved").Where(m => m.Availability != "Available").ToList();
                ViewBag.PageCount = new SelectList(generatePageList(getPage(model.Count())), "Text", "Text");



                if (page == 1)
                {
                    int totalskip = page * totaltake;
                    return View(model.Take(totaltake).ToList());
                }
                else if (page == 2)
                {
                    int totalskip = totaltake;
                    return View(model.Skip(totalskip).Take(totaltake).ToList());
                }
                else
                {
                    int totalskip = (page - 1) * totaltake;
                    return View(model.Skip(totalskip).Take(totaltake).ToList());
                }
            }
            else if (String.IsNullOrEmpty(category) && !String.IsNullOrEmpty(condition))
            {
                var model = ItemsVm.Where(m => m.condition == condition).Where(m => m.isApproved == "Approved").Where(m => m.Availability != "Sold").ToList();
                ViewBag.PageCount = new SelectList(generatePageList(getPage(model.Count())), "Text", "Text");



                if (page == 1)
                {
                    int totalskip = page * totaltake;
                    return View(model.Take(totaltake).ToList());
                }
                else if (page == 2)
                {
                    int totalskip = totaltake;
                    return View(model.Skip(totalskip).Take(totaltake).ToList());
                }
                else
                {
                    int totalskip = (page - 1) * totaltake;
                    return View(model.Skip(totalskip).Take(totaltake).ToList());
                }

            }
            else
            {
                var model = ItemsVm.OrderBy(m => m.isPremium).Where(m => m.isApproved == "Approved").Where(m => m.Availability != "Sold").ToList();

                ViewBag.PageCount = new SelectList(generatePageList(getPage(ItemsVm.Where(m => m.isApproved == "Approved").Where(m => m.Availability != "Sold").Count())), "Text", "Text");

OnlineStore/Controllers/ItemTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineStore.Models;

namespace OnlineStore.Controllers
{
    public class ItemTypesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ItemTypes
        public ActionResult Index()
        {
            return View(db.ItemType.ToList());
        }

        // GET: ItemTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemType itemType = db.ItemType.Find(id);
            if (itemType == null)
            {
                return HttpNotFound();
            }
            return View(itemType);
        }

        // GET: ItemTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ItemTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ItemTypeID,ItemTypeName")] ItemType itemType)
        {
            if (ModelState.IsValid)
            {
                db.ItemType.Add(itemType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(itemType);
        }

        // GET: ItemTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemType itemType = db.ItemType.Find(id);
            if (itemType == null)
            {
                return HttpNotFound();
            }
            return View(itemType);
        }

        // POST: ItemTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ItemTypeID,ItemTypeName")] ItemType itemType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(itemType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(itemType);
        }

        // GET: ItemTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemType itemType = db.ItemType.Find(id);
            if (itemType == null)
            {
                return HttpNotFound();
            }
            return View(itemType);
        }

        // POST: ItemTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ItemType itemType = db.ItemType.Find(id);
            db.ItemType.Remove(itemType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineStore/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<div class="container">
    <div class="coming-soon-placeholder" style="display:table"></div>
</div>

OnlineStore/Views/Home/Chat.cshtml
@model OnlineStore.Models.Chat
@{
    ViewBag.Title = "Chat";
}
<div class="container"><br />
    <input type="hidden" id="displayname" />
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                   <h4>Message</h4> 
                </div>
                <div class="panel-body">
         
                        <textarea type="text" class="form-control" id="message"></textarea>
       
        <br />
                        <input type="button" id="sendmessage" value="Send"  class="btn btn-default"/>
          
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>Message Feed</h4>
                </div>
                <div class="panel-body" style="height:500px; overflow-y:scroll">
                    <ul id="discussion"></ul>
                </div>
            </div>
        </div>
    </div>





</div>
@section scripts {
    <!--Script references. -->
    <!--The jQuery library is required and is referenced by default in _Layout.cshtml. -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="~/signalr/hubs"></script>
    <!--SignalR script to update the chat page and send messages.-->
    <script>
        $(function () {
            // Reference the auto-generated proxy for the hub.
            var chat = $.connection.chatHub;
            // Create a function that the hub can call back to display messages.
            chat.client.addNewMessageToPage = function (name, message) {
                // Add the message to the page.
                $('#discussion').append('<li><strong>' + htmlEncode(name)
                    + '</strong>: ' + htmlEncode(message) + '</li>');
            };
            // Get the user name and store it to prepend to messages.
            $('#displayname').val(prompt('Enter your name:', '@ViewBag.Email'));
          
            // Set initial focus to message input box.
            $('#message').focus();
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#sendmessage').click(function () {
                    // Call the Send method on the hub.
                    chat.server.send($('#displayname').val(), $('#message').val());
                    // Clear text box and reset focus for next comment.
                    $('#message').val('').focus();
                });
            });
        });
        // This optional function html-encodes messages for display in the page.
        function htmlEncode(value) {
            var encodedValue = $('<div />').text(value).html();
            return encodedValue;
        }
    </script>
}

OnlineStore/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<div class="container">
    <div class="coming-soon-placeholder" style="display:table"></div>
</div>

OnlineStore/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Frontpage.cshtml";
}
@using Microsoft.AspNet.Identity

<div style="margin-bottom:50px;">
    <div class="home-wallpaper" style="display:table">
        <div class="home-filter">
            <div class="jumbotron" style="background:none;">
                <div class="container">
                    <div class="hero-banner">
                        <h1>JAM-Tag</h1>
                        <p style="padding:20px;">JAM-Tag is an online store that lets you post your items for sale and make it available for public to view.</p>
                        <br />
                        @if (ViewBag.IsLoggedIn == false)
                        {
                            <a class="ghostbutton" href="@Url.Action("Login","Account")">Log In</a>
                            <a class="ghostbutton" href="@Url.Action("Register","Account")">Sign Up</a>
                        }
                        else
                        {
                            <a class="ghostbutton" href="@Url.Action("Chat")">Live Chat</a>
                            if (ViewBag.IsAdmin == true)
                            {
                                <a class="ghostbutton" href="@Url.Action("ItemsToApprove","Item")">Approve Items</a>
                                <a class="ghostbutton" href="@Url.Action("Index","ItemTypes")">Add Item Type</a>

                            }
                            <a class="ghostbutton" href="@Url.Action("LogOff", "Account")">Log Out</a>
                        }




                        <a class="ghostbutton" href="#helpsection">Help</a>
                        <a class="ghostbutton" data-toggle="modal" data-target="#termsModal">Terms &amp; Agreement</a>

                    </div>
                    <div class="categories-banner visible-lg visible-md">
                        Search By:
                        <ul id="category-list">
                            <li data-toggle="tooltip" data-placement="top" title="Mobile"><a href="@Url.Action("ViewItems", "Item", new { @category="Mobile" })"><i class="ion-iphone icons"></i></a></li>
                            <li data-toggle="tooltip" data-placement="top" title="Computers"><a href="@Url.Action("ViewItems", "Item", new { @category="Computers" })"><i class="ion-monitor icons"></i></a></li>
                            <li data-toggle="tooltip" data-placement="top" title="Pets"><a href="@Url.Action("ViewItems", "Item", new { @category="Pets" })"><i class="ion-ios-paw icons"></i></a></li>
                            <li data-toggle="tooltip" data-placement="top" title="Hobbies"><a href="@Url.Action("ViewItems", "Item", new { @category="Hobbies" })"><i class="ion-ios-basketball-outline icons"></i></a></li>
                            <li data-toggle="tooltip" data-placement="top" title="Motorcycles"><a href="@Url.Action("ViewItems", "Item", new { @category="Motorcycles" })"><i class="ion-android-bicycle icons"></i></a></li>
                            <li data-toggle="tooltip" data-placement="top" title="Home Appliances"><a href="@Url.Action("ViewItems", "Item", new { @category = "Home Appliances" })"><i class="ion-home icons"></i></a></li>
                            <li data-toggle="tooltip" data-placement="top" title="Furniture"><a href="@Url.Action("ViewItems", "Item", new { @category="Furniture" })"><i class="ion-trophy icons"></i></a></li>
                            <li data-toggle="tooltip" data-placement="top" title="Cars"><a href="@Url.Action("ViewItems", "Item", new { @category="Cars" })"><i class="ion-model-s icons"></i></a></li>
                            <li data-toggle="tooltip" data-placement="top" title="Fashion"><a href="@Url.Action("ViewItems", "Item", new { @category = "Fashion" })"><i class="ion-tshirt icons"></i></a></li>
                        </ul>
                        <br />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="thumbnail">
                <center>
                    <img src="~/Images/earth1.png" alt="..." style="width:auto; height:120px;">

                    <div class="caption">

                        <h1>Post your Item</h1>
                        <p>
                            Jam Tag is an online store that lets you post your items  and make it available for public to view.
                        </p>
                        <br />
                        <p><a class="ghostbuttonblack" href="/Item/AddItems">Add your items!</a></p>
                    </div>
                </center>
            </div>
        </div>
        <div class="col-md-4">
            <div class="thumbnail">
                <center>
                    <img src="~/Images/shoppingcart36.png" alt="..." style="width:auto; height:120px;">

                    <div class="caption">
                        <h1>View Items for Sale</h1>
                        <p>By just visiting Jam Tag, you can access a wide variety of items that is available posted by users</p>
                        <br />
                        <p><a class="ghostbuttonblack" href="/Item/ViewItems">See items for sale!</a></p>
                    </div>
                </center>
            </div>
        </div>
        <div class="col-md-4">
            <div class="thumbnail">
                <center>
                    <img src="~/Images/checked33.png" alt="..." style="width:auto; height:120px;">
                    <div class="caption">
                        <h1>Manage your items</h1>
                        <p>You can also manage your items easily in a single page. How cool is that?!</p>
                        <br />
                        <p><a class="ghostbuttonblack" href="/Manage">Manage your items!</a></p>
                    </div>
                </center>
            </div>
        </div>
    </div>
</div>
<br />
<div class="programmersection">
    <div class="home-filter">
        <div class="container">
            <div class="row">
                <h1 style="color:white; font-weight:100; text-align:center">The Programmers</h1>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="filtergray">
                        <div class="thumbnail" style="background:none; border:none ">
                            <img src="~/Images/ipsum.jpg" style="width: 150px; height: 150px; border-radius: 50%;" />
                            <h2>Mark B. Sancon</h2>
                            <p></p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="filtergray">
                        <div class="thumbnail" style="background:none; border:none ">
                            <img src="~/Images/lorem.jpg" style="width: 150px; height: 150px; border-radius: 50%;" />
                            <h2>Aki S. Watanabe</h2>
                            <p></p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="filtergray">
                        <div class="thumbnail" style="background:none; border:none ">
                            <img src="~/Images/dolor.jpg" style="width: 150px; height: 150px; border-radius: 50%;" />
                            <h2>Jesman A. Lantican</h2>
                            <p></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="locateus">
    <div class="container">
        <div class="col-md-offset-1 col-md-3">
            <center> <h1>Our Location</h1></center>
            <p>
                Lynville Homes Subd Phase IV, Bagumbayan,
                Santa Cruz, Laguna
            </p>
            <p><span class="glyphicon glyphicon-phone-alt"></span> : 879-8777 </p>
            <p><span class="glyphicon glyphicon-phone"></span> : 0987-856-8975 </p>
            <p><span class="glyphicon glyphicon-envelope"></span> : JamTag@JamTag.com</p>
        </div>
        <div class="col-md-8">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7733.317135165495!2d121.39365289109946!3d14.273123371402427!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3397e3099d0d0c33%3A0xc696a86d71553654!2sLynville+Homes+Subd+Phase+IV!5e0!3m2!1sen!2sph!4v1449205375994" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
    </div>

</div>

<div class="quickhelp" id="helpsection" style="background:#e3e3e3;">
    <div class="container">
        <center>
            <h1>Quick Guide</h1>
        </center>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    How to add an item
                </div>
                <div class="panel-body">
                    <ol>
                        <li>The user should be logged in</li>
                        <li>Click the "Add your items!" button located at the View Items for Sale block</li>
                        <li>Fill up the details and click save</li>
                        <li>Wait for you item to be approved by our administrator</li>
                    </ol>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Buying Item
                </div>
                <div class="panel-body">

                    <ol>
                        <li>The user should be logged in</li>
                        <li>Click the "Manage your item!" button located at the post your item block</li>
                        <li>Use the "Filter by"" panel to search and filter the items</li>
                        <li>Click the item that you are interested with</li>
                        <li>Click the Paypal Buy Now button that is located in the right side of the item name</li>
                    </ol>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Managing your item
                </div>
                <div class="panel-body">

                    <ol>
                        <li>The user should be logged in</li>
                        <li>Click the "See items for sale!" button located at the Manage your items block</li>
                        <li>the the "My Items For Sale" Panel Choose the item you want to manage</li>
                        <li>Update the selected item and click Save</li>
                        <li>Wait for our adminstrator to approve your updated item</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

</div>
@section scripts
{
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    @*<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>*@
    <script>
    
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();

            $.ajax({
                url: '/AdminReport/WebViewCount/',
                method: 'GET',
                success: function (data) {

                }
            });
        })
    </script>
}